not supporting oxygen 23 in version 0.3.1 any more due to build errors
build error with `mvn -Doxygen.verions=23 clean package`:

Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project icu-xpath-bindings: Compilation failure
Error:  /home/runner/work/icu-xpath-bindings/icu-xpath-bindings/bindings/src/main/java/de/wwu/scdh/xpath/icu/text/TransliteratorIds.java:[81,36] cannot find symbol
Error:    symbol:   method concatenate(net.sf.saxon.value.StringValue)
Error:    location: variable output of type net.sf.saxon.om.GroundedValue
Error:  -> [Help 1]
Error:
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :icu-xpath-bindings
Error: Process completed with exit code 1.